INSERT INTO TABLE_USER(USERNAME,EMAIL,PASSWORD,IS_ADMIN) VALUES ('Admin','admin@tvz.hr','admin123',TRUE);
INSERT INTO TABLE_USER(USERNAME,EMAIL,PASSWORD,IS_ADMIN) VALUES ('Matija','matija@tvz.hr','matija123',FALSE);

INSERT INTO TABLE_ALBUM(NAME,ARTIST,ID_USER) VALUES ('Blonde','Frank Ocean',1);
INSERT INTO TABLE_ALBUM(NAME,ARTIST,ID_USER) VALUES ('Blonde','Frank Ocean',2);
INSERT INTO TABLE_ALBUM(NAME,ARTIST,ID_USER) VALUES ('Schengengang','High 5',2);
INSERT INTO TABLE_ALBUM(NAME,ARTIST,ID_USER) VALUES ('Man On the Moon 3: The Chosen','Kid Cudi',2);
INSERT INTO TABLE_ALBUM(NAME,ARTIST,ID_USER) VALUES ('DAMN.','Kendrick Lamar',2);